--[[ TODO
-- Create directory for my secrets and establish a symlink from config file to actual secret
-- Start scripting in bash. Make utility scripts. It takes way too long to get my applications set up the way I want them
-- Add a bash function which pip installs and saves to requirements.txt in venv file
-- Find way to list all of the breakpoints. Might be able to use quickfix list
-- install neorg for better notetaking
-- Find way to trigger nvim when searching for directories through Fzf. Maybe set a keybind which triggers fzf dir finder then immediately triggers nvim with the result. Check this out: https://github.com/junegunn/fzf?tab=readme-ov-file#turning-into-a-different-process
-- get a jupyter notebook alternative installed through neovim
-- use vim be good and practice
--    - Get better at relative line jumps
-- create a bash script that will completely install all the dev dependencies needed to get started
--  - need to figure out how to deal with git submodules and worktrees
--  - Add a symlink for my work .zshrc so I have a copy. I did some cool stuff in it. **Seperate by branch**
--  - create something like from folke -> https://github.com/folke/dot/tree/master/nvim
--  - add .txt file explaining everything I need to do to get everything up and running
--  - create a gitrepo around my config
--  - find a way to include .zshrc, .tmux.conf and neovim config entirely inside a git repo so it can be version controlled
--  - create bash script which installs all dev dependencies via homebrew
--  - add executable script which will isntall all the dependencies I need to get started
-- find helpful keymaps for lsp. Especially one which jumps forward and backwards to different functions --> can use <leader>ss
-- Learn basic syntax of lua
------ debugging lua files https://zignar.net/2023/06/10/debugging-lua-in-neovim/
-- extend the github command in command line and have it except pull request numbers to save me some clicks
-- Need formatting for .tmpl and vars fileshttps://gecgithub01.walmart.com/SRE/production-playbooks/pull/48702
-- Need to learn how to use copilot more effectively. Still kinda slow with it
--    - See how I can get agent mode working in codecompanion if it's even setup
-- Make netrw open instead of lazy distro on startup
-- Nerd fonts collection https://www.nerdfonts.com/font-downloads
-- <leader>d is slow on my mac when editing python files. Need to fix this
-- Fix WSL loading non ubuntu window on startup
-- Job still running error when I try to wqa. Suspect it's the formatting on save
-- Create notes repo and install a markdown plugin which exports to obsidian so I can get the foam graph
-- Find a way to get PR notes directly into my editor
--  - I can use the following github command:
--    - gh api repos/:owner/:repo/pulls/1/comments --paginate \ jq '.[] | {path, line, author: .user.login, body}'  --jq '.[] | {path, line, author: .user.login, body}'
--
--
-- DONE:
-- Fix readme file parsing. I always get errors when trying to open README files -> DONE
-- Python formatting doesn't work on save, need to fix this -> DONE
-- Make stack trace links to files open neovim file instead of vscode -> DONE. Go to iterm2 -> profiles -> advanced -> semantic history -> Run coprocess $echo nvim \1:\2 -> This will make stack trace links open in neovim
-- Disable warnings from LSP. Especially in Readme files -> Can use leader<ud>
-- ]]

-- bootstrap lazy.nvim, LazyVim and your plugins
-- Format on save is broken for python files
-- NOTE:
--  - if tests aren't discoverable make sure to run :TSInstall <language>
--  - golang debugger doesn't work with 1.25
--  - If you need to update plugins comment out the copilot
--  - change fonts in iterm https://www.nerdfonts.com/font-downloads

require("config.lazy")
