-- return {
--   "folke/sidekick.nvim",
--   enabled = false,
--   init = function()
--     vim.lsp.enable("copilot")
--   end,
--   opts = {
--     log_level = "error"
--   },
--   dependencies = {
--     "github/copilot.vim",
--     opts = {
--       log_level = "error"
--     }
--   }
-- }
return {
  "github/copilot.vim",
  -- config = function()
  --   -- Disable copilot suggestions in the completion menu
  --   vim.g.copilot_no_tab_map = false
  --   vim.g.copilot_assume_mapped = true
  --   vim.g.copilot_tab_fallback = ""
  --   
  --   -- Set up tab to accept copilot suggestions
  --   vim.api.nvim_set_keymap("i", "<Tab>", 'copilot#Accept("<Tab>")', { silent = true, expr = true, script = true })
  --   
  --   -- Optional: Add keymaps for navigating between suggestions
  --   vim.api.nvim_set_keymap("i", "<M-]>", "<Plug>(copilot-next)", { silent = true })
  --   vim.api.nvim_set_keymap("i", "<M-[>", "<Plug>(copilot-previous)", { silent = true })
  --   vim.api.nvim_set_keymap("i", "<M-\\>", "<Plug>(copilot-suggest)", { silent = true })
  -- end,
}
